import 'package:shop/Model/productmodel.dart';

class Productcontroller {
  final List<ProductModel> products = [
    ProductModel(
      code: 1,
      name: "iPhone 17 PM",
      category: "assets/image/apple.jpg",
      oldprice: 1299,
      discount: 10,
      image: "assets/image/17pm_white.jpg",
      quantity: 1,
      rate: "4.9",
      view: "12.5K",
      description:
          "Powerful iPhone with premium design and advanced camera system.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Natural Titanium", "Blue Titanium", "Black Titanium"],
      detail_item: [
        "assets/image/17pm_1.jpg",
        "assets/image/17pm_2.jpg",
        "assets/image/17pm_3.jpg",
        "assets/image/17pm_4.jpg",
      ],
      detail_sp: [
        "6.9-inch Super Retina XDR display",
        "A19 Pro chip with advanced Neural Engine",
        "Pro camera system with 48MP main camera",
        "Titanium design with Action Button",
      ],
    ),
    ProductModel(
      code: 2,
      name: "iPhone 15 Pro",
      category: "assets/image/apple.jpg",
      oldprice: 999,
      discount: 8,
      image: "assets/image/15pro.jpg",
      quantity: 1,
      rate: "4.8",
      view: "10.2K",
      description: "Powerful iPhone with A17 Pro chip and professional camera.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Natural Titanium", "Blue Titanium", "Black Titanium"],
      detail_item: [
        "assets/image/15pro_1.jpg",
        "assets/image/15pro_2.jpg",
        "assets/image/15pro_3.jpg",
        "assets/image/15pro_4.jpg",
      ],
      detail_sp: [
        "6.1-inch Super Retina XDR display",
        "A17 Pro chip",
        "Pro camera system (48MP main)",
        "Titanium design with USB-C",
      ],
    ),
    ProductModel(
      code: 3,
      name: "iPhone 15 Plus",
      category: "assets/image/apple.jpg",
      oldprice: 899,
      discount: 7,
      image: "assets/image/15pro.jpg",
      quantity: 1,
      rate: "4.7",
      view: "8.6K",
      description: "Large display iPhone with excellent battery life.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Pink", "Blue", "Green"],
      detail_item: [
        "assets/image/15plus_1.jpg",
        "assets/image/15plus_2.jpg",
        "assets/image/15plus_3.jpg",
        "assets/image/15plus_4.jpg",
      ],
      detail_sp: [
        "6.7-inch Super Retina XDR display",
        "A16 Bionic chip",
        "48MP main camera",
        "All-day battery life",
      ],
    ),
    ProductModel(
      code: 4,
      name: "Galaxy S24 Ultra",
      category: "assets/image/samsung.jpg",
      oldprice: 1299,
      discount: 10,
      image: "assets/image/25ul.jpg",
      quantity: 1,
      rate: "4.9",
      view: "18.4K",
      description: "Flagship Samsung phone with 200MP camera and S Pen.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "Gray", "Violet"],
      detail_item: [
        "assets/image/s24u_1.jpg",
        "assets/image/s24u_2.jpg",
        "assets/image/s24u_3.jpg",
        "assets/image/s24u_4.jpg",
      ],
      detail_sp: [
        "6.8-inch Dynamic AMOLED 2X display",
        "Snapdragon 8 Gen 3 for Galaxy",
        "200MP main camera + S Pen",
        "Titanium frame & IP68",
      ],
    ),
    ProductModel(
      code: 5,
      name: "Galaxy S25 ultra",
      category: "assets/image/samsung.jpg",
      oldprice: 999,
      discount: 8,
      image: "assets/image/24ul.jpg",
      quantity: 1,
      rate: "4.8",
      view: "14.2K",
      description:
          "Samsung flagship with AMOLED display and powerful performance.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "Violet", "Gray"],
      detail_item: [
        "assets/image/s25u_1.jpg",
        "assets/image/s25u_2.jpg",
        "assets/image/s25u_3.jpg",
        "assets/image/s25u_4.jpg",
      ],
      detail_sp: [
        "6.8-inch Dynamic AMOLED 2X",
        "Latest Snapdragon / Exynos flagship chip",
        "200MP camera system",
        "Built-in S Pen support",
      ],
    ),
    ProductModel(
      code: 6,
      name: "Galaxy S26 Ultra",
      category: "assets/image/samsung.jpg",
      oldprice: 1199,
      discount: 15,
      image: "assets/image/26ul.jpg",
      quantity: 1,
      rate: "4.9",
      view: "21.5K",
      description: "Samsung phone with 200MP camera and built-in S Pen.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Green", "Black", "Cream"],
      detail_item: [
        "assets/image/s26u_1.jpg",
        "assets/image/s26u_2.jpg",
        "assets/image/s26u_3.jpg",
        "assets/image/s26u_4.jpg",
      ],
      detail_sp: [
        "6.9-inch Dynamic AMOLED 2X display",
        "Next-gen Snapdragon chipset",
        "200MP camera + advanced AI",
        "S Pen + Armor Aluminum frame",
      ],
    ),
    ProductModel(
      code: 7,
      name: "Xiaomi 14 Ultra",
      category: "assets/image/mi.jpg",
      oldprice: 999,
      discount: 10,
      image: "assets/image/xi14.jpg",
      quantity: 1,
      rate: "4.8",
      view: "11.3K",
      description:
          "Xiaomi flagship with Leica camera and powerful performance.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "White", "Blue"],
      detail_item: [
        "assets/image/xi14_1.jpg",
        "assets/image/xi14_2.jpg",
        "assets/image/xi14_3.jpg",
        "assets/image/xi14_4.jpg",
      ],
      detail_sp: [
        "6.73-inch LTPO AMOLED display",
        "Snapdragon 8 Gen 3",
        "Leica optical camera system",
        "120W HyperCharge support",
      ],
    ),
    ProductModel(
      code: 8,
      name: "Ximi14",
      category: "Xiaomi 17 Ultra",
      oldprice: 799,
      discount: 8,
      image: "assets/image/xi17.jpg",
      quantity: 1,
      rate: "4.7",
      view: "8.9K",
      description:
          "Xiaomi flagship phone with AMOLED display and Leica camera.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Black", "White", "Green"],
      detail_item: [
        "assets/image/xi17_1.jpg",
        "assets/image/xi17_2.jpg",
        "assets/image/xi17_3.jpg",
        "assets/image/xi17_4.jpg",
      ],
      detail_sp: [
        "6.7-inch AMOLED display",
        "High-performance chipset",
        "Leica-tuned camera",
        "Fast charging support",
      ],
    ),
    ProductModel(
      code: 9,
      name: "Redmi",
      category: "assets/image/mi.jpg",
      oldprice: 499,
      discount: 15,
      image: "assets/image/pro2.jpg",
      quantity: 1,
      rate: "4.6",
      view: "13.5K",
      description: "Redmi phone with 200MP camera and AMOLED display.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Black", "White", "Purple"],
      detail_item: [
        "assets/image/redmi_1.jpg",
        "assets/image/redmi_2.jpg",
        "assets/image/redmi_3.jpg",
        "assets/image/redmi_4.jpg",
      ],
      detail_sp: [
        "6.67-inch AMOLED display",
        "200MP main camera",
        "Fast charging support",
        "High refresh rate screen",
      ],
    ),
    ProductModel(
      code: 10,
      name: "OPPO Find X7UT",
      category: "assets/image/oppo.jpg",
      oldprice: 999,
      discount: 10,
      image: "assets/image/oppox7.jpg",
      quantity: 1,
      rate: "4.8",
      view: "9.8K",
      description: "OPPO flagship with advanced camera system.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "Blue", "Brown"],
      detail_item: [
        "assets/image/findx7_1.jpg",
        "assets/image/findx7_2.jpg",
        "assets/image/findx7_3.jpg",
        "assets/image/findx7_4.jpg",
      ],
      detail_sp: [
        "6.78-inch AMOLED display",
        "Advanced Hasselblad / OPPO camera",
        "Flagship chipset",
        "SuperVOOC fast charging",
      ],
    ),
    ProductModel(
      code: 11,
      name: "OPPO Reno 12P",
      category: "assets/image/oppo.jpg",
      oldprice: 599,
      discount: 12,
      image: "assets/image/oppo_reno12.jpg",
      quantity: 1,
      rate: "4.6",
      view: "8.4K",
      description: "OPPO phone with stylish design and AI camera features.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Black", "Silver", "Purple"],
      detail_item: [
        "assets/image/reno12_1.jpg",
        "assets/image/reno12_2.jpg",
        "assets/image/reno12_3.jpg",
        "assets/image/reno12_4.jpg",
      ],
      detail_sp: [
        "6.7-inch AMOLED display",
        "AI portrait camera",
        "Stylish slim design",
        "Fast charging support",
      ],
    ),
    ProductModel(
      code: 12,
      name: "OPPO Reno 11",
      category: "assets/image/oppo.jpg",
      oldprice: 449,
      discount: 10,
      image: "assets/image/OPPO Reno 11.jpg",
      quantity: 1,
      rate: "4.5",
      view: "7.3K",
      description: "OPPO phone with AMOLED display and fast charging.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Black", "Green", "Gold"],
      detail_item: [
        "assets/image/reno11_1.jpg",
        "assets/image/reno11_2.jpg",
        "assets/image/reno11_3.jpg",
        "assets/image/reno11_4.jpg",
      ],
      detail_sp: [
        "6.7-inch AMOLED display",
        "Portrait-focused camera",
        "Fast charging support",
        "Slim and lightweight design",
      ],
    ),
    ProductModel(
      code: 13,
      name: "vivo X300 Pro",
      category: "assets/image/vivo.jpg",
      oldprice: 899,
      discount: 10,
      image: "assets/image/vivox300.jpg",
      quantity: 1,
      rate: "4.8",
      view: "12.1K",
      description: "vivo flagship with ZEISS camera and powerful performance.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "Blue", "White"],
      detail_item: [
        "assets/image/x300_1.jpg",
        "assets/image/x300_2.jpg",
        "assets/image/x300_3.jpg",
        "assets/image/x300_4.jpg",
      ],
      detail_sp: [
        "6.78-inch AMOLED display",
        "ZEISS optics camera system",
        "Flagship performance chipset",
        "Fast charging & long battery",
      ],
    ),
    ProductModel(
      code: 14,
      name: "vivo V40 Pro",
      category: "assets/image/vivo.jpg",
      oldprice: 599,
      discount: 12,
      image: "assets/image/vivo V40 Pro.jpg",
      quantity: 1,
      rate: "4.7",
      view: "9.5K",
      description: "vivo phone with ZEISS portrait camera and fast charging.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Gray", "White", "Purple"],
      detail_item: [
        "assets/image/v40_1.jpg",
        "assets/image/v40_2.jpg",
        "assets/image/v40_3.jpg",
        "assets/image/v40_4.jpg",
      ],
      detail_sp: [
        "6.78-inch AMOLED display",
        "ZEISS portrait camera",
        "Fast charging support",
        "Stylish design with premium build",
      ],
    ),
  ];
}
