import 'package:shop/Model/productmodel.dart';

class Productcontroller {
  final List<ProductModel> products = [
    ProductModel(
      code: 1,
      name: "iPhone 17 PM",
      category: "assets/image/apple.jpg",
      oldprice: 1299,
      discount: 10,
      image: "assets/image/17pm_white.jpg",
      quantity: 1,
      rate: "4.9",
      view: "12.5K",
      description:
          "Powerful iPhone with premium design and advanced camera system.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Natural Titanium", "Blue Titanium", "Black Titanium"],
    ),
    ProductModel(
      code: 2,
      name: "iPhone 15 Pro",
      category: "assets/image/apple.jpg",
      oldprice: 999,
      discount: 8,
      image: "assets/image/15pro.jpg",
      quantity: 1,
      rate: "4.8",
      view: "10.2K",
      description: "Powerful iPhone with A17 Pro chip and professional camera.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Natural Titanium", "Blue Titanium", "Black Titanium"],
    ),
    ProductModel(
      code: 3,
      name: "iPhone 15 Plus",
      category: "assets/image/apple.jpg",
      oldprice: 899,
      discount: 7,
      image: "assets/image/15pro.jpg",
      quantity: 1,
      rate: "4.7",
      view: "8.6K",
      description: "Large display iPhone with excellent battery life.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Pink", "Blue", "Green"],
    ),

    ProductModel(
      code: 4,
      name: "Galaxy S24 Ultra",
      category: "assets/image/samsung.jpg",
      oldprice: 1299,
      discount: 10,
      image: "assets/image/25ul.jpg",
      quantity: 1,
      rate: "4.9",
      view: "18.4K",
      description: "Flagship Samsung phone with 200MP camera and S Pen.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "Gray", "Violet"],
    ),

    ProductModel(
      code: 5,
      name: "Galaxy S25 ultra",
      category: "assets/image/samsung.jpg",
      oldprice: 999,
      discount: 8,
      image: "assets/image/24ul.jpg",
      quantity: 1,
      rate: "4.8",
      view: "14.2K",
      description:
          "Samsung flagship with AMOLED display and powerful performance.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "Violet", "Gray"],
    ),

    ProductModel(
      code: 6,
      name: "Galaxy S26 Ultra",
      category: "assets/image/samsung.jpg",
      oldprice: 1199,
      discount: 15,
      image: "assets/image/26ul.jpg",
      quantity: 1,
      rate: "4.9",
      view: "21.5K",
      description: "Samsung phone with 200MP camera and built-in S Pen.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Green", "Black", "Cream"],
    ),

    ProductModel(
      code: 7,
      name: "Xiaomi 14 Ultra",
      category: "assets/image/mi.jpg",
      oldprice: 999,
      discount: 10,
      image: "assets/image/xi14.jpg",
      quantity: 1,
      rate: "4.8",
      view: "11.3K",
      description:
          "Xiaomi flagship with Leica camera and powerful performance.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "White", "Blue"],
    ),

    ProductModel(
      code: 8,
      name: "Ximi14",
      category: "Xiaomi 17 Ultra",
      oldprice: 799,
      discount: 8,
      image: "assets/image/xi17.jpg",
      quantity: 1,
      rate: "4.7",
      view: "8.9K",
      description:
          "Xiaomi flagship phone with AMOLED display and Leica camera.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Black", "White", "Green"],
    ),

    ProductModel(
      code: 9,
      name: "Redmi",
      category: "assets/image/mi.jpg",
      oldprice: 499,
      discount: 15,
      image: "assets/image/pro2.jpg",
      quantity: 1,
      rate: "4.6",
      view: "13.5K",
      description: "Redmi phone with 200MP camera and AMOLED display.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Black", "White", "Purple"],
    ),

    ProductModel(
      code: 10,
      name: "OPPO Find X7UT",
      category: "assets/image/oppo.jpg",
      oldprice: 999,
      discount: 10,
      image: "assets/image/oppox7.jpg",
      quantity: 1,
      rate: "4.8",
      view: "9.8K",
      description: "OPPO flagship with advanced camera system.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "Blue", "Brown"],
    ),

    ProductModel(
      code: 11,
      name: "OPPO Reno 12P",
      category: "assets/image/oppo.jpg",
      oldprice: 599,
      discount: 12,
      image: "assets/image/oppo_reno12.jpg",
      quantity: 1,
      rate: "4.6",
      view: "8.4K",
      description: "OPPO phone with stylish design and AI camera features.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Black", "Silver", "Purple"],
    ),

    ProductModel(
      code: 12,
      name: "OPPO Reno 11",
      category: "assets/image/oppo.jpg",
      oldprice: 449,
      discount: 10,
      image: "assets/image/OPPO Reno 11.jpg",
      quantity: 1,
      rate: "4.5",
      view: "7.3K",
      description: "OPPO phone with AMOLED display and fast charging.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Black", "Green", "Gold"],
    ),

    ProductModel(
      code: 13,
      name: "vivo X300 Pro",
      category: "assets/image/vivo.jpg",
      oldprice: 899,
      discount: 10,
      image: "assets/image/vivox300.jpg",
      quantity: 1,
      rate: "4.8",
      view: "12.1K",
      description: "vivo flagship with ZEISS camera and powerful performance.",
      storage: ["256GB", "512GB", "1TB"],
      color: ["Black", "Blue", "White"],
    ),
    ProductModel(
      code: 14,
      name: "vivo V40 Pro",
      category: "assets/image/vivo.jpg",
      oldprice: 599,
      discount: 12,
      image: "assets/image/vivo V40 Pro.jpg",
      quantity: 1,
      rate: "4.7",
      view: "9.5K",
      description: "vivo phone with ZEISS portrait camera and fast charging.",
      storage: ["128GB", "256GB", "512GB"],
      color: ["Gray", "White", "Purple"],
    ),
  ];
}
