import 'package:shop/Model/productmodel.dart';
class Productcontroller {
  final List<ProductModel> products = [
    // ==================== APPLE ====================
    ProductModel(
      code: 1,
      name: "iPhone 17 Pro Max",
      category: "assets/image/apple.jpg",
      oldprice: 1299,
      discount: 10,
      image: "assets/image/17pm_white.jpg",
      quantity: 1,
      rate: "4.9",
      view: "12.5K",
      description:
          "Powerful iPhone with premium design and advanced camera system.",
      storage: "128GB",
      color: "White",
      detail_item: [
        "assets/image/mh.jpg",
        "assets/image/jkj.jpg",
        "assets/image/de3_17.jpg",
        "assets/image/de2_17.jpg",
      ],
      detail_sp: [
        "6.9-inch Super Retina XDR display",
        "A19 Pro chip with advanced Neural Engine",
        "Pro camera system with 48MP main camera",
        "Titanium design with Action Button",
      ],
    ),
    ProductModel(
      code: 2,
      name: "iPhone 17 Pro Max",
      category: "assets/image/apple.jpg",
      oldprice: 1299,
      discount: 10,
      image: "assets/image/17pm_orange.jpg",
      quantity: 1,
      rate: "4.9",
      view: "12.5K",
      description:
          "Powerful iPhone with premium design and advanced camera system.",
      storage: "128GB",
      color: "Orange",
      detail_item: [
        "assets/image/17pm_orange_de1.jpg",
        "assets/image/orangede2.jpg",
      //   "assets/image/de3_17.jpg",
      //   "assets/image/de2_17.jpg",
      ],
      detail_sp: [
        "6.9-inch Super Retina XDR display",
        "A19 Pro chip with advanced Neural Engine",
        "Pro camera system with 48MP main camera",
        "Titanium design with Action Button",
      ],
    ),
    ProductModel(
      code: 3,
      name: "Fold 7",
      category: "assets/image/apple.jpg",
      oldprice: 1299,
      discount: 10,
      image: "assets/image/fold71.jpg",
      quantity: 1,
      rate: "4.9",
      view: "12.5K",
      description:
          "Powerful iPhone with premium design and advanced camera system.",
      storage: "128GB",
      color: "Orange",
      detail_item: [
        "assets/image/fold72.jpg",
        "assets/image/fold7.jpg",
      //   "assets/image/de3_17.jpg",
      //   "assets/image/de2_17.jpg",
      ],
      detail_sp: [
        "6.9-inch Super Retina XDR display",
        "A19 Pro chip with advanced Neural Engine",
        "Pro camera system with 48MP main camera",
        "Titanium design with Action Button",
      ],
    ),

    ProductModel(
      code: 3,
      name: "iPhone 13",
      category: "assets/image/apple.jpg",
      oldprice: 999,
      discount: 8,
      image: "assets/image/13 pink.jpg",
      quantity: 1,
      rate: "4.8",
      view: "10.2K",
      description: "iPhone 13 with a 6.1-inch Super Retina XDR OLED display, powerful performance, and an advanced dual-camera system.",
      storage: "128GB",
      color: "Pink",
      detail_item: [
        "assets/image/13pinkDe.jpg",
        "assets/image/13de2.jpg",
        "assets/image/13pinkde2.jpg",
      ],
      detail_sp: [
        "6.1-inch Super Retina XDR display",
        "A15 Bionic chip",
        "12MP dual-camera system",
        "All-day battery life",
      ],
    ),

    ProductModel(
      code: 4,
      name: "iPhone 17",
      category: "assets/image/apple.jpg",
      oldprice: 999,
      discount: 8,
      image: "assets/image/17machta.jpg",
      quantity: 1,
      rate: "4.8",
      view: "10.2K",
      description: "Modern iPhone with a premium design, powerful performance, and advanced camera system.",
      storage: "128GB",
      color: "Matcha",
      detail_item: [
        "assets/image/matchade.jpg",
        // "assets/image/13pinkde1.jpg",
        // "assets/image/17maccha_de2.jpg",
      ],
      detail_sp: [
        "Super Retina XDR display",
        "High-performance Apple chip",
        "Advanced camera system",
        "Premium aluminum design",
      ],
    ),

    ProductModel(
      code: 5,
      name: "iPhone 17 Duo",
      category: "assets/image/apple.jpg",
      oldprice: 999,
      discount: 8,
      image: "assets/image/duma.jpg",
      quantity: 1,
      rate: "4.8",
      view: "10.2K",
      description: "iPhone with a premium display, powerful performance, and advanced camera system.",
      storage: "128GB",
      color: "Matcha",
      detail_item: [
        "assets/image/duo_de.jpg",
        "assets/image/duo_de1.jpg",
        "assets/image/duo_de2.jpg",
      ],
      detail_sp: [
        "Super Retina XDR display",
        "High-performance Apple chip",
        "Pro camera system",
        "USB-C connectivity",
      ],
    ),

    ProductModel(
      code: 6,
      name: "iPhone 16 Plus",
      category: "assets/image/apple.jpg",
      oldprice: 899,
      discount: 7,
      image: "assets/image/16plus.jpg",
      quantity: 1,
      rate: "4.7",
      view: "8.6K",
      description: "iPhone 16 Plus with a 6.7-inch Super Retina XDR display, A18 chip, 48MP Fusion camera, Camera Control, and long battery life.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/16de2.jpg",
        "assets/image/16de3.jpg",
        "assets/image/16de4.jpg",
      ],
      detail_sp: [
        "6.7-inch Super Retina XDR display",
        "A18 chip",
        "48MP Fusion camera",
        "Up to 27 hours video playback",
      ],
    ),

    ProductModel(
      code: 7,
      name: "iPhone 17 Air",
      category: "assets/image/apple.jpg",
      oldprice: 999,
      discount: 10,
      image: "assets/image/17ari.jpg",
      quantity: 1,
      rate: "4.8",
      view: "15.2K",
      description: "Slim and lightweight iPhone with a modern design and powerful performance.",
      storage: "128GB",
      color: "White",
      detail_item: [
        "assets/image/air_de1.jpg",
        "assets/image/17ari_de2.jpg",
        
      ],
      detail_sp: [
        "Slim premium design",
        "High-performance Apple chip",
        "Advanced camera system",
        "Long battery life",
      ],
    ),

    // ==================== SAMSUNG ====================
    ProductModel(
      code: 8,
      name: "Galaxy S24 Ultra",
      category: "assets/image/samsung.jpg",
      oldprice: 1299,
      discount: 10,
      image: "assets/image/25ul.jpg",
      quantity: 1,
      rate: "4.9",
      view: "18.4K",
      description: "Samsung flagship smartphone with a premium display, powerful processor, advanced camera system, and built-in S Pen.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/s24de3.jpg",
        "assets/image/s24de2.jpg",
        "assets/image/s24de1.jpg",
        //"assets/image/s24u_4.jpg",
      ],
      detail_sp: [
        "6.8-inch Dynamic AMOLED 2X display",
        "Snapdragon 8 Gen 3 for Galaxy",
        "200MP main camera",
        "Built-in S Pen",
      ],
    ),
    ProductModel(
      code: 9,
      name: "Galaxy S25 Ultra",
      category: "assets/image/samsung.jpg",
      oldprice: 999,
      discount: 8,
      image: "assets/image/24ul.jpg",
      quantity: 1,
      rate: "4.8",
      view: "14.2K",
      description: "Samsung flagship with a premium AMOLED display, powerful performance, advanced camera system, and S Pen support.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/s25de1.jpg",
        "assets/image/s25de2.jpg",
        // "assets/image/s25u_3.jpg",
        // "assets/image/s25u_4.jpg",
      ],
      detail_sp: [
        "6.8-inch Dynamic AMOLED 2X",
        "Flagship Snapdragon chipset",
        "200MP camera system",
        "Built-in S Pen support",
      ],
    ),

    ProductModel(
      code: 10,
      name: "Galaxy S26 Ultra",
      category: "assets/image/samsung.jpg",
      oldprice: 1199,
      discount: 15,
      image: "assets/image/26ul.jpg",
      quantity: 1,
      rate: "4.9",
      view: "21.5K",
      description: "Samsung flagship smartphone with a large AMOLED display, powerful chipset, advanced camera system, and S Pen.",
      storage: "128GB",
      color: "Black",
      detail_item: ["assets/image/s26de1.jpg", "assets/image/s26de2.jpg","assets/image/s26de3.jpg"],
      detail_sp: [
        "6.9-inch Dynamic AMOLED 2X display",
        "Next-generation Snapdragon chipset",
        "200MP camera with advanced AI",
        "S Pen support",
      ],
    ),

    // ==================== XIAOMI ====================
    ProductModel(
      code: 11,
      name: "Xiaomi 14 Ultra",
      category: "assets/image/mi.jpg",
      oldprice: 999,
      discount: 10,
      image: "assets/image/xi14.jpg",
      quantity: 1,
      rate: "4.8",
      view: "11.3K",
      description: "Xiaomi flagship smartphone with Leica camera technology and powerful performance.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/xiaomi14de.jpg",
        // "assets/image/xi14_2.jpg",
        // "assets/image/xi14_3.jpg",
        // "assets/image/xi14_4.jpg",
      ],
      detail_sp: [
        "6.73-inch LTPO AMOLED display",
        "Snapdragon 8 Gen 3",
        "Leica camera system",
        "120W HyperCharge support",
      ],
    ),

    ProductModel(
      code: 12,
      name: "Xiaomi 17 Ultra",
      category: "assets/image/mi.jpg",
      oldprice: 799,
      discount: 8,
      image: "assets/image/xi17.jpg",
      quantity: 1,
      rate: "4.7",
      view: "8.9K",
      description: "Xiaomi flagship phone with AMOLED display, powerful performance, and Leica camera technology.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/xi17_1.jpg",
        "assets/image/xi17_2.jpg",
        "assets/image/xi17_3.jpg",
        "assets/image/xi17_4.jpg",
      ],
      detail_sp: [
        "6.7-inch AMOLED display",
        "High-performance chipset",
        "Leica-tuned camera",
        "Fast charging support",
      ],
    ),

    ProductModel(
      code: 13,
      name: "Redmi K100",
      category: "assets/image/k1000.jpg",
      oldprice: 499,
      discount: 15,
      image: "assets/image/k1000.jpg",
      quantity: 1,
      rate: "4.6",
      view: "13.5K",
      description: "Redmi smartphone with a high-resolution camera, AMOLED display, and fast charging.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/k100_de1.jpg",
        "assets/image/k100_de2.jpg",
        "assets/image/k100.jpg",
        //"assets/image/redmi_4.jpg",
      ],
      detail_sp: [
        "6.67-inch AMOLED display",
        "200MP main camera",
        "Fast charging support",
        "High refresh rate display",
      ],
    ),

    // ==================== OPPO ====================
    ProductModel(
      code: 14,
      name: "OPPO Find X7 Ultra",
      category: "assets/image/oppo.jpg",
      oldprice: 999,
      discount: 10,
      image: "assets/image/oppox7.jpg",
      quantity: 1,
      rate: "4.8",
      view: "9.8K",
      description: "OPPO flagship smartphone with an advanced camera system and powerful performance.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/findx7_1.jpg",
        "assets/image/findx7_2.jpg",
        "assets/image/findx7_3.jpg",
        "assets/image/findx7_4.jpg",
      ],
      detail_sp: [
        "6.78-inch AMOLED display",
        "Advanced OPPO camera system",
        "Flagship chipset",
        "SuperVOOC fast charging",
      ],
    ),

    ProductModel(
      code: 15,
      name: "OPPO Reno 12 Pro",
      category: "assets/image/oppo.jpg",
      oldprice: 599,
      discount: 12,
      image: "assets/image/oppo_reno12.jpg",
      quantity: 1,
      rate: "4.6",
      view: "8.4K",
      description: "OPPO smartphone with stylish design, AMOLED display, and AI camera features.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/reno12_1.jpg",
        "assets/image/reno12_2.jpg",
        "assets/image/reno12_3.jpg",
        "assets/image/reno12_4.jpg",
      ],
      detail_sp: [
        "6.7-inch AMOLED display",
        "AI portrait camera",
        "Slim premium design",
        "Fast charging support",
      ],
    ),

    ProductModel(
      code: 16,
      name: "OPPO Reno 11",
      category: "assets/image/oppo.jpg",
      oldprice: 449,
      discount: 10,
      image: "assets/image/OPPO Reno 11.jpg",
      quantity: 1,
      rate: "4.5",
      view: "7.3K",
      description: "OPPO smartphone with AMOLED display, portrait camera, and fast charging.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/reno11_1.jpg",
        "assets/image/reno11_2.jpg",
        "assets/image/reno11_3.jpg",
        "assets/image/reno11_4.jpg",
      ],
      detail_sp: [
        "6.7-inch AMOLED display",
        "Portrait-focused camera",
        "Fast charging support",
        "Slim and lightweight design",
      ],
    ),
    // ==================== VIVO ====================
    ProductModel(
      code: 17,
      name: "vivo X300 Pro",
      category: "assets/image/vivo.jpg",
      oldprice: 899,
      discount: 10,
      image: "assets/image/vivox300.jpg",
      quantity: 1,
      rate: "4.8",
      view: "12.1K",
      description: "vivo flagship smartphone with ZEISS camera technology and powerful performance.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/v300de1.jpg",
        "assets/image/v300de2.jpg",
        // "assets/image/x300_3.jpg",
        // "assets/image/x300_4.jpg",
      ],
      detail_sp: [
        "6.78-inch AMOLED display",
        "ZEISS camera system",
        "Flagship performance chipset",
        "Fast charging and long battery life",
      ],
    ),

    ProductModel(
      code: 18,
      name: "vivo X200 Pro",
      category: "assets/image/vivo.jpg",
      oldprice: 599,
      discount: 12,
      image: "assets/image/v200.jpg",
      quantity: 1,
      rate: "4.7",
      view: "9.5K",
      description: "vivo smartphone with ZEISS portrait camera, premium design, and fast charging.",
      storage: "128GB",
      color: "Black",
      detail_item: [
        "assets/image/v40_1.jpg",
        "assets/image/v40_2.jpg",
        "assets/image/v40_3.jpg",
        "assets/image/v40_4.jpg",
      ],
      detail_sp: [
        "6.78-inch AMOLED display",
        "ZEISS portrait camera",
        "Fast charging support",
        "Premium stylish design",
      ],
    ),
  ];
}
