// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjvjGkGHc7oSB5zC7wVJnObrd5FL5OMyA',
    appId: '1:127842104726:web:41d2c46a6c78c38e0c59b7',
    messagingSenderId: '127842104726',
    projectId: 'shopapp-85bc7',
    authDomain: 'shopapp-85bc7.firebaseapp.com',
    storageBucket: 'shopapp-85bc7.firebasestorage.app',
    measurementId: 'G-DV9FSRMWDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-mktm2f_hV8_Jt3EJKLi-YdyTexU7uw',
    appId: '1:127842104726:android:4ae62fb6fb308ccb0c59b7',
    messagingSenderId: '127842104726',
    projectId: 'shopapp-85bc7',
    storageBucket: 'shopapp-85bc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaFPrSg1Ywk2RBKHtDyFjgvjomNYmbws',
    appId: '1:127842104726:ios:39c28f259914e36b0c59b7',
    messagingSenderId: '127842104726',
    projectId: 'shopapp-85bc7',
    storageBucket: 'shopapp-85bc7.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMaFPrSg1Ywk2RBKHtDyFjgvjomNYmbws',
    appId: '1:127842104726:ios:39c28f259914e36b0c59b7',
    messagingSenderId: '127842104726',
    projectId: 'shopapp-85bc7',
    storageBucket: 'shopapp-85bc7.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjvjGkGHc7oSB5zC7wVJnObrd5FL5OMyA',
    appId: '1:127842104726:web:2d0d5b0d5876ebdb0c59b7',
    messagingSenderId: '127842104726',
    projectId: 'shopapp-85bc7',
    authDomain: 'shopapp-85bc7.firebaseapp.com',
    storageBucket: 'shopapp-85bc7.firebasestorage.app',
    measurementId: 'G-G4TBCX2B44',
  );
}
