import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:shop/Mainhomepage.dart';
import 'package:shop/auth/authservice.dart';
import 'package:shop/auth/signinscreen.dart';
import 'package:shop/bloc/shop_bloc.dart';
import 'package:shop/firebase_options.dart'; // generated by `flutterfire configure`
/// true  = app ALWAYS opens on Sign in (good for testing)
/// false = app remembers the login and opens the home screen directly
const bool kAlwaysStartAtSignIn = true;
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  if (kAlwaysStartAtSignIn) {
    await FirebaseAuth.instance.signOut();
  }
  runApp(
    // The bloc sits ABOVE MaterialApp so every screen can read it.
    MultiBlocProvider(
      providers: [BlocProvider<ShopBloc>(create: (_) => ShopBloc())],
      child: const MyApp(),
    ),
  );
}
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: StreamBuilder<User?>(
        stream: AuthService.instance.authChanges,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          // Logged in -> home screen, otherwise -> Sign in
          return snapshot.hasData ? const Mainhomepage() : SignInScreen();
        },
      ),
    );
  }
}
