import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:shop/Mainhomepage.dart';
import 'package:shop/auth/authservice.dart';
import 'package:shop/auth/signinscreen.dart';
import 'package:shop/bloc/shop_bloc.dart';
import 'package:shop/firebase_options.dart'; // generated by `flutterfire configure`
/// true  = app ALWAYS opens on Sign in (good for testing)
/// false = app remembers the login and opens the home screen directly
const bool kAlwaysStartAtSignIn = true;
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Silence a known, benign Flutter engine bug: it fires when the mouse
  // hovers over a widget that gets removed from the tree mid-animation
  // (closing a dialog / bottom sheet / route transition). It doesn't affect
  // app behavior — it's just noisy in the debug console.
  final originalOnError = FlutterError.onError;
  FlutterError.onError = (FlutterErrorDetails details) {
    final String text = details.exceptionAsString();
    final bool isKnownHarmlessMouseTrackerBug = text.contains('mouse_tracker.dart') ||
        text.contains('Cannot hit test a render box with no size') ||
        text.contains('Cannot hit test a render box that has never been laid out');
    if (isKnownHarmlessMouseTrackerBug) {
      // Swallow it silently instead of printing to the console.
      return;
    }

    // Every other error still behaves normally.
    if (originalOnError != null) {
      originalOnError(details);
    } else {
      FlutterError.presentError(details);
    }
  };

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  if (kAlwaysStartAtSignIn) {
    await FirebaseAuth.instance.signOut();
  }
  runApp(
    // The bloc sits ABOVE MaterialApp so every screen can read it.
    MultiBlocProvider(
      providers: [BlocProvider<ShopBloc>(create: (_) => ShopBloc())],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: StreamBuilder<User?>(
        stream: AuthService.instance.authChanges,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          // Logged in -> home screen, otherwise -> Sign in
          return snapshot.hasData ? const Mainhomepage() : Mainhomepage();
        },
      ),
    );
  }
}